[project]
name = "kubernetes-notebook"
version = "0.1.0"
description = "Kubernetes Jupyter Notebook"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.5",
    "notebook>=7.4.4",
]
